### ISSUE TITLE
Main Application Container

### ISSUE THREAD

**Issue by ShaneClancy** [oceanboard/oceanboard#3]
Create application container than can host columns.

**Comment by mi11y** [comment]
Namely https://valadoc.org/gtk+-3.0/Gtk.Layout.html

**Comment by mi11y** [comment]
Ended up using Gtk.Box and Gtk.ListBox

**Comment by mi11y** [comment]
![image](https://user-images.githubusercontent.com/26660036/77836125-a9c69280-7110-11ea-9c52-5853e9a6ba49.png)
